### ISSUE TITLE
Animations for modal analysis

### ISSUE THREAD

**Issue by carlomontec** [imirzov/ccx2paraview#1]
Hi, the VTU tool also is able to animate modal analyses?

Thank you for your great work!

**Comment by imirzov** [comment]
Hi,
I haven't tried modal analysis in CalculiX. But you can ))
Please, then post your response about conversion.

**Comment by imirzov** [comment]
Dear Carlo,

Animation is not the matter of the converter. It should be done by Paraview based on calculated displacement fields. [Here is what I've found](https://public.kitware.com/pipermail/paraview/2017-October/041077.html) as the workaround for mode shapes animation. For me it works perfect!

**Comment by carlomontec** [comment]
Thanks for the hint and your great work!

**Comment by Nidish96** [comment]
I tried this out for modal analysis but I found all the files greyed out in paraview when I open the resulting vtu files (or vtk).

Let me know what can be done.

Thank you very much for this

**Comment by imirzov** [comment]
Dear Nidish,
Please, could you attach a screenshot?
The description of your problem is quite poor.
What does it mean "files are greyed out"?
