### ISSUE TITLE
Pyinstaller do not work with Python 3.8

### ISSUE THREAD

**Issue by TEFEdotCC** [imirzov/ccx2paraview#11]
The command
```console
pyinstaller src/ccx2paraview.py --onefile
```
runs successfull. But in a fresh console I get
```console
ccx2paraview ....frd vtk
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pkg_resources/__init__.py", line 84, in <module>
ModuleNotFoundError: No module named 'packaging.requirements'
[12] Failed to execute script pyi_rth_pkgres
```

**Comment by TEFEdotCC** [comment]
Actually I'm not sure src folder is the reason.
I add two hidden import commands and its seem to work correctly

```console
pyinstaller --onefile src/ccx2paraview.py --hidden-import 'packaging.requirements' --hidden-import 'pkg_resources.py2_warn'
```

**Comment by imirzov** [comment]
Hi, thanks for checking it! Yesterday I've forgotten to update developer's section in the README.md:
https://github.com/calculix/ccx2paraview#for-developers

Now it's OK. And everything works fine.

Commands for the converter:
python3 ./src/ccx2paraview.py jobname.frd vtu
python3 ./src/ccx2paraview.py jobname.frd vtk

Command for pyInstaller:
pyinstaller ./src/ccx2paraview.py --onefile
[pyinstaller.log](https://github.com/calculix/ccx2paraview/files/4748066/pyinstaller.log)

**Comment by TEFEdotCC** [comment]
```bash
> pyinstaller ./src/ccx2paraview.py --onefile
```
builds successfull, but can not be executed.
[pyinstaller.log](https://github.com/calculix/ccx2paraview/files/4750157/pyinstaller.log)
```bash
> python --version
Python 3.8.3
> pyinstaller --version
3.6
```

```bash
> dist/ccx2paraview 
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/pkg_resources/__init__.py", line 84, in <module>
ModuleNotFoundError: No module named 'packaging.requirements'
[4338] Failed to execute script pyi_rth_pkgres
```

**Comment by imirzov** [comment]
After building a binary I ran:
`./dist/ccx2paraview`

And got:
`usage: ccx2paraview [-h] filename format`
`ccx2paraview: error: the following arguments are required: filename, format`

So, for me it works. But I have Python 3.6.9 and pyinstaller 3.5.

**Comment by imirzov** [comment]
Aha! Read here: https://www.pyinstaller.org/downloads.html
`Release 3.6: stable, supports Python 2.7, 3.5–3.7`
So, do not hurry to update your Python.

**Comment by TEFEdotCC** [comment]
Thanks, good to know.
It seems the development of pyinstaller stucks :(
