### ISSUE TITLE
ERROR: Numpy is not installed

### ISSUE THREAD

**Issue by Raphadw** [imirzov/ccx2paraview#12]
Good afternoon,

First I would like to thank you about the great job you are doing on this project.

I try to convert a calculix .frd file with the excutable ccx2paraview.exe. My issue is that I have an error (Numpy).

Can you give me an advice about to solve this issue. I tkink I am doing something wrong.

Thank you.

Raphaël

Here after the message :

C:\Users\RA\Documents\09_OUTILS_BE\calculix_\1\ccx2.16orig>ccx2paraview.exe fichier_parameter.frd vtu
INFO: Parsing fichier_parameter.frd
INFO: 192 nodes
INFO: 75 cells
INFO: Step 1, time 1.0, U, 3 components, 0 values
ERROR: Numpy is not installed.
Additional stresses will not be appended.
INFO: Step 1, time 1.0, S, 6 components, 0 values
ERROR: Numpy is not installed.
Additional strains will not be appended.
INFO: Step 1, time 1.0, E, 6 components, 0 values
INFO: 1 time increment
INFO: Writing fichier_parameter.vtu
INFO: Step 1, time 1.0, U, 3 components, 192 values
INFO: Step 1, time 1.0, S, 6 components, 192 values
INFO: Step 1, time 1.0, E, 6 components, 192 values

**Comment by imirzov** [comment]
Hi,

Thank you for using this converter and posting issues!

It's strange that executable asks for numpy. Looks like I've missed something while created the executable. Nevertheless, you need Python3 installed on your OS with _numpy_ library. Run this command to install _numpy_:

`pip install numpy`
or
`pip3 install numpy`

Without this library converter will not append equivalent and principal stresses and strains. I hope you know that CalculiX CrunchiX doesn't calculate them.

Good luck!

**Comment by Raphadw** [comment]
Hello,
I have done a new installation of python on my OS windows10 and I have also install Numpy. The excutable still doesn't work.
I solved the problem running directly the python script. Hereafter the command :
python ccx2paraview.py fichier_parameter.frd vtu

Regards.

**Comment by Nils-Holgerson** [comment]
I have the same problem with numpy modul. The exe is not working and running the py file does not work either :(

**Comment by Raphadw** [comment]
Hello,
You have Just to move the py file out from thé current directory. It should
work. If no, tonight i Will send you more détails.
Regards

Le lun. 22 juin 2020 14:31, Nils-Holgerson <notifications@github.com> a
écrit :

**Comment by Nils-Holgerson** [comment]
I figured it out. It is more a numpy problem than a problem with the converter itself. Creating a project in pycharm with all .py files in it, adjusting the imports and loading numpy in the project environment solved it.

**Comment by imirzov** [comment]
Guys, possibly it's not a problem at all. What you see is just command print() informing that you have no numpy installed. But numpy goes with converter's binary (inside of it).

Please, open the conversion result in Paraview and have a look if it has a Mises Stress field. If it has, just ignore the error. If no - the error report has sense and I'll try to fix it.

**Comment by imirzov** [comment]
Check previous comment, then, please, test those binaries:
[ccx2paraview_ubuntu_20200622.zip](https://github.com/calculix/ccx2paraview/files/4814467/ccx2paraview_ubuntu_20200622.zip)
[ccx2paraview_windows_20200622.zip](https://github.com/calculix/ccx2paraview/files/4814469/ccx2paraview_windows_20200622.zip)

**Comment by imirzov** [comment]
Fixed numpy for Windows:
https://github.com/calculix/ccx2paraview/releases/tag/v2.3.1
