### ISSUE TITLE
Export tensors as tensors

### ISSUE THREAD

**Issue by peterheppel** [imirzov/ccx2paraview#13]
Hi there.
Thanks for this utility. It's great to find something which simply works without hassle.  (ubuntu 16.04)
Here's a feature suggestion:  Its great to have the derived stress quantities, but if we want to do things like 3D glyph plots of stress we would need the stress tensor. Of course we can reconstruct it with the programmable filter but it would be great not to need that. 
One small question:  does ccx2paraview assume that the node numbering and/or element numbering are contiguous?  I work  from CAD files and end up zapping a lot of element sets. This leaves gaps and I suspect that ccx2paraview doesnt allow that. 

Best,Peter

**Comment by imirzov** [comment]
Dear Peter,

I don't believe in suspects. If ccx2paraview doesn't work for contiguous nodes/elements numbering, - please, attach some logs.

And yep, it's great to do things like 3D glyph plots. But how? Do you have an example model? I'm not a Paraview user.

**Comment by peterheppel** [comment]
Dear Ihor,
I checked out the ‘suspicion’ and I was wrong.  The model which led to the suspicion was trash in other ways.  Sorry.  Here is a test suite in which I have changed the numbering of one of the standard ccx tests

Re: glyphs and things in Paraview.  Excuse me if I tell you things which you know.

The way paraview works is that after you load your data, you can display it directly or you can build up a tree of ‘Filters’  to change what is shown and how.  Each filter modifies the data or how it is represented.
For example  to smooth out (and lose detail) you might add a PointDatatoCellData filter to the dataset, then add a CellDatatoPointData filter to that.  Or you can use the Glyph filter for a vector plot.

Paraview expects data on the cells and nodes to be either scalar, vector (2 or 3) , or tensor(2,2) or (3,3) .  A glyph plot of stress (for example)  will only come out right in 3D  if the stress is a 3x3 tensor.

The ccx stress components are the lower triangle of the stress tensor which is {{Sxx, Sxy,Sxz},{Syz,Syy,Syz},{Szx,Szy,Szz}} where Sxy=Syz, etc.   Formally, this quantity is the Cauchy stress tensor. It is symmetric.
https://en.wikipedia.org/wiki/Cauchy_stress_tensor

I’m not sure whether when there are *ORIENTATIONS  ccx maps stress to the global axes before writing.

What you might like to do is to export the stress and strain tensors as their own datasets, in addition to the specific quantities which ccx displays
As a work-around, if I feel the need I can use the pv ‘Programmable Python Filter’ to build up the stress tensor from the six components.
Thanks for a great utility!
Peter


Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.

**Comment by imirzov** [comment]
![stress](https://user-images.githubusercontent.com/4652710/90988416-e0ef8180-e592-11ea-8428-ebefe6e73191.png)

Dear Peter,

Now I'm working on version 3.0 of the converter and would like to implement your requested feature. Please, have a look on a test model - [stress.zip](https://github.com/calculix/ccx2paraview/files/5114953/stress.zip) - it has only one tet element with 4 stress tensors defined at each node. I do not understand what 3D-glyphs are visualizing? I expected 3 arrows per node - each arrow should be aligned to eigenvector of the stress tensor.

What I'm doing wrong? Please, could you post corrected VTU file with a screenshot of how 3D-glyphs should look like.

**Comment by peterheppel** [comment]
Dear Ihor,

The format of the vtu file looks correct.
The only thing is that you need to use the TensorGlyph filter. I think you used the Glyph filter.
I modified the stress to make it less uniform. Here is my vtu file and a paraview screenshot.
Congratulations! This will be a big help. It opens up all sorts of things like streamline plots, as well as custom processing using Python.  If there isn’t already a vonMises stress filter, for example, I could write one for you.
Already there

Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.

**Comment by imirzov** [comment]
Sorry, Peter,
Where are your files?

**Comment by peterheppel** [comment]
Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.

**Comment by imirzov** [comment]
Nope :(

Looks like you're using Outlook. Please, visit [the thread](https://github.com/calculix/ccx2paraview/issues/13) and have a look on what you're posting.

**Comment by peterheppel** [comment]
<?xml version="1.0"?>
<VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian" header_type="UInt32" compressor="vtkZLibDataCompressor">
  <UnstructuredGrid>
    <Piece NumberOfPoints="4" NumberOfCells="1">
      <PointData Tensors="S">
        <DataArray type="Float64" Name="S" NumberOfComponents="9" format="ascii" RangeMin="0" RangeMax="3" ComponentName0="xx" ComponentName1="xy" ComponentName2="xz" ComponentName3="yx" ComponentName4="yy" ComponentName5="yz" ComponentName6="zx" ComponentName7="zy" ComponentName8="zz">
          0 0 0 0 0 0 0 0 0
          10 0 0 0 1 0 0 0 1
          2 0 0 0 20 0 0 0 2
          .3 0 0 0 3 0 0 0 30
        </DataArray>
      </PointData>
      <CellData>
      </CellData>
      <Points>
        <DataArray type="Float32" Name="Points" NumberOfComponents="3" format="ascii" RangeMin="1" RangeMax="2.6381811790024576">
          0 0 1 1.4 1 2
          1.4 1 0 0 2 1
        </DataArray>
      </Points>
      <Cells>
        <DataArray type="Int64" Name="connectivity" format="ascii" RangeMin="0" RangeMax="3">
          0 1 2 3
        </DataArray>
        <DataArray type="Int64" Name="offsets" format="ascii" RangeMin="4" RangeMax="4">
          4
        </DataArray>
        <DataArray type="UInt8" Name="types" format="ascii" RangeMin="10" RangeMax="10">
          10
        </DataArray>
      </Cells>
    </Piece>
  </UnstructuredGrid>
</VTKFile>

[cid:image003.jpg@01D67AD4.223D0C90]


Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.

**Comment by peterheppel** [comment]
Did you get the last? I in-lined the VTU and picture

Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.

**Comment by imirzov** [comment]
Thank you, I've got code of the .vtu file.
But no image - please, do not use mail clients. Post directly to GitHub here:
https://github.com/calculix/ccx2paraview/issues/13

I've visualized your .vtu file - it doesn't seem to be useful for stress field analysis:
![tensor_glyph](https://user-images.githubusercontent.com/4652710/91206712-dd313b80-e707-11ea-9410-47cc74afe342.png)

**Comment by peterheppel** [comment]
Hi Ihor,
That looks correct - and useful.  Here is a fuller version 
![ScreenshotParaview](https://user-images.githubusercontent.com/69041999/91208324-a8a18d80-e6cf-11ea-864a-3d3d13649f3e.png)

**Comment by imirzov** [comment]
Looks like I've got it. Thank you!
![tadam](https://user-images.githubusercontent.com/4652710/91210116-03a5a580-e70d-11ea-81d2-1d7fe2a766a6.png)
A new release will be soon.

**Comment by imirzov** [comment]
Dear Peter,

Please, test new version:
https://github.com/calculix/ccx2paraview/releases/tag/v3.0.0

**Comment by peterheppel** [comment]
Hi Ihor,

V 3.0.0 is really nice. I’ve been using it as standard so I can post-process my Calculix work in Paraview.

Here’s a suggestion:  It would be great if  you could include an integer scalar containing each element’s  GROUP,  or MATERIAL.

Another dataset which I find really useful is the element’s material tangent stiffness tensor. Easiest for the paraview user would be to provide it  in the (deflected)  global cartesian frame.
This dataset is useful for  checking input data for anisotropic materials, as well as for the stuff I do with inverse design of fields of this tensor.
But it’s a lot more work to produce, especially with nonlinear materials.
It’s almost as useful to see the highest principal value of the stiffness, as a scalar or a vector. (but for the vector you need to do the transformation)

Just thinking aloud. Thanks again for a great utility.

Peter




Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.

**Comment by imirzov** [comment]
Hi Peter,
Thank you for using the utility. I'll save your suggestions to implements sometimes later.

**Comment by peterheppel** [comment]
Good to hear from you.  If I get a chance I might try to add it.


Peter Heppel
Technology Fellow
Studio Gang
1520 W. Division Street
Chicago, IL 60642
+1 872 315 2211
+1 773 502 4336 cell
+1 773 384 1212
studiogang.com<../../../../../dgraham/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2324AUMM/studiogang.com>

This transmission may contain information that is privileged, confidential, or exempt from disclosure. If you are not the intended recipient, your disclosure, copying, distribution, or use of the information contained herein is prohibited. If you received this transmission in error, contact the sender and delete the material.
