### ISSUE TITLE
The executable looks for exactly python37

### ISSUE THREAD

**Issue by aomanchuria** [imirzov/ccx2paraview#17]
Could this be changed to use a generic python via PYTHONHOME?

**Comment by imirzov** [comment]
ihor@alkor: echo $PYTHONHOME

ihor@alkor: python -V
Python 2.7.18
ihor@alkor: python3 -V
Python 3.8.5

So, I haven't variable PYTHONHOME, my Python version is not 3.7, but the converter works fine.
