### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by emilio-martin** [imirzov/ccx2paraview#18]
I would like to know if you are going to provide a binary release (bin) of the ccx2paraview application, as you did with 2.3.1. In any case, thank you very much for your contribution.

**Comment by imirzov** [comment]
Hi,

Latest version is 3.0.0. Sources and binaries are uploaded here:
https://github.com/calculix/ccx2paraview/releases/tag/v3.0.0

Linux binary:
https://github.com/calculix/ccx2paraview/releases/download/v3.0.0/ccx2paraview_20200829_linux.zip

Windows binary:
https://github.com/calculix/ccx2paraview/releases/download/v3.0.0/ccx2paraview_20200829_windows.zip

**Comment by emilio-martin** [comment]
Thanks a lot. I had already tried it before. But it doesn't work for me. On the other hand, version 2.3.1 contained in the (bin) folder of the zip file does work correctly. I guess it has to do with the fact that I don't have Python installed under Windows. Could it be that this version requires some component that I don't have?

**Comment by imirzov** [comment]
In theory binary doesn't need installed Python. If it doesn't work, you could provide some logging information regarding errors.

**Comment by emilio-martin** [comment]
First I run it with a .bat file (which does work in the bin directory of version 2.3.1), with the following code:
ccx2paraview.exe input3.frd vtu
The system (windows 10) shows the error window that I show in the capture, and that I translate below:
"Code execution cannot continue because python37.dll was not found. This problem can be solved by reinstalling the program."
![SNAG-0000](https://user-images.githubusercontent.com/77229075/104230729-3cd97a80-544e-11eb-9257-ace95bd7eebf.jpg)

On the other hand, if I execute the same sentence in the command window, you can see in the second screenshot that the system shows another error message, and suggests executing the following:
.\ccx2paraview.exe input3.frd vtu
This way, no error is displayed, but no file is generated either.
![SNAG-0001](https://user-images.githubusercontent.com/77229075/104231258-fafd0400-544e-11eb-8385-c15fbcacbe6f.jpg)

I don't know if this will be enough for you to understand what is happening. In any case, I really appreciate your interest.

**Comment by imirzov** [comment]
Unfortunately, we can only ask Bill Gates why PowerShell and cmd.exe give different results. I'd rather work with cmd. And try to install latest Python 3. Hope it'll help.

Your case seems to be irrelevant to the converter itself. So I can not help, sorry. Consider stop using Windows. Linux is much better for scientists, engineers and programmers.

**Comment by emilio-martin** [comment]
In any case, thank you very much for your work.

**Comment by emilio-martin** [comment]
I comment only for your knowledge. I have installed the current version of Python (3.9.1), and I have also tried 3.7.9 since the system asked for the phyton37.dll library. In both cases it has not worked. Indeed, you are right. I would like to be able to work in Linux, but in my position we use many applications that will not work under Linux except with an emulator. And also, my university has opted for Office365 systems. I have no other options.
In any case, I am surprised that version 2.3.1 of the application in the bin folder has two files (ccx2paraview.exe 6Mb and ccx2paraview 23.4Mb), while 3.0.0 only has the executable (with 18.4Mb). I do not know if it is relevant, but it catches my attention.
Anyway, thank you very much for your time and interest.

**Comment by imirzov** [comment]
It's a pity that you haven't succeeded to run the converter.
ccx2paraview v2.3.1 was created with pyinstaller, while v3.0.0 - with nuitka. That's why binary file size is different.
ccx2paraview v2.3.1 for Windows was compiled without numpy, while Linux version - with it. As you can see, numpy is quite 'heavy' library.
