### ISSUE TITLE
Elements C3D20 have flipped vertices

### ISSUE THREAD

**Issue by carlomontec** [imirzov/ccx2paraview#2]
Hi,
when I plot a mesh using Hexa quads C3D20's, I can see that the element is built with some wrong order in the node list, making them to look somehow twisted. This is the same both in VTk and VTU scripts.

Edite: Corrected type from C3D30s to C3D20's

**Comment by imirzov** [comment]
Hi!
Could you, please, share your .frd-file? Quad hex should be C3D20, doesn't it? In FRDParser see FRDElem class: there is no '30' in 'nodesPerType' variable.

**Comment by SergioP1975** [comment]
I agree with Carlomontec, there are some quads that looks weird

Check my CCX input file: (zipped, 1.4 Mb)
https://drive.google.com/open?id=1yx-LPVaS5VXCMvDJwm0JoiLkU6KrtA0M

Or directly the CCX results in .frd: (zipped, 74 Mb)
https://drive.google.com/open?id=18RWaMqY4LQPwXiucFAhJvIWBRAP7N609

Some pictures:

This is with your conversor
![Ccx2Paraview](https://user-images.githubusercontent.com/50833189/58023475-4201ed00-7ae6-11e9-82a3-f642f19b37ee.png)

This is with Calmed
![Calmed](https://user-images.githubusercontent.com/50833189/58023521-5e058e80-7ae6-11e9-923b-8a6bc84f1233.png)


By the way, could be the file generated as a timed series of data? Looks like is easier to change between modes, and then the time value is usefull for putting a text showing the frecuencie.

Regards

**Comment by carlomontec** [comment]
@imirzov  I made a mistake, its C3D20 elements.  The output looks very similar to @SergioP1975, where the elements corner are correctly defined, but the faces are built in a wrong ordering of nodes per face. I am almost sure that the numbering of the nodes while building the cubic element are not correct. I will try to make a PR, if I manage to get some time :)

**Comment by imirzov** [comment]
![paraview](https://user-images.githubusercontent.com/4652710/58372098-29943700-7f19-11e9-83df-988dcf1e413f.png)

Thank you, guys! Hope, this bug is fixed now!
Please, check a new version: https://github.com/imirzov/ccx2paraview

Sergio, now converter creates separate files per each step/frequency.
