### ISSUE TITLE
Does it support VTK 9.0.1?

### ISSUE THREAD

**Issue by ceanwang** [imirzov/ccx2paraview#20]
Can't use: 
`pip3 install VTK`
to install VTK on Win 10 Ver 1909. It says:

````
  ERROR: Could not find a version that satisfies the requirement VTK (from versions: none)
ERROR: No matching distribution found for VTK

```

**Comment by imirzov** [comment]
Use lowercase:
`pip3 install numpy vtk ccx2paraview`

**Comment by ceanwang** [comment]
Same.

The others installed. Just vtk can't.

**Comment by imirzov** [comment]
Sorry, your problem is not relevant to ccx2paraview converter.
You may ask your windows administrator why OS can't install VTK.

**Comment by ceanwang** [comment]
The administrator can do nothing. Just pip can't find a right version.
My question is Does ccx2paraview converter support VTK 9.0.1?

**Comment by imirzov** [comment]
Yes. I have vtk 9.0.1 and the converter works fine:
```
pip3 install vtk
Requirement already satisfied: vtk in ./.local/lib/python3.8/site-packages (9.0.1)
```

**Comment by ceanwang** [comment]
Tried again. It is different now: Collecting vtk  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03F2AAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/vtk/ Just pip can’t work for this big package. Maybe my network is not good. Sent from Mail for Windows 10 From: Ihor MirzovSent: Friday, March 26, 2021 7:34 AMTo: calculix/ccx2paraviewCc: ceanwang; AuthorSubject: Re: [calculix/ccx2paraview] Does it support VTK 9.0.1? (#20) Yes. I have vtk 9.0.1 and the converter works fine:pip3 install vtkRequirement already satisfied: vtk in ./.local/lib/python3.8/site-packages (9.0.1)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
