### ISSUE TITLE
there is no application to open then shared file

### ISSUE THREAD

**Issue by DRsunday401** [imirzov/ccx2paraview#26]
![1647315350(1)](https://user-images.githubusercontent.com/96322339/158301195-821fcedb-bac5-49a0-ad9b-c4d135711a40.png)

i dont kown what's going wrong!

**Comment by imirzov** [comment]
Dear DRsunday401,

Sorry for late response.  Looks like you're trying to open ccx2paraview with a double click. But ccx2paraview is a console/terminal utility without GUI. So run it from terminal, like it is written in the documentation:
https://github.com/calculix/ccx2paraview#how-to-use
