### ISSUE TITLE
Nodes and elements are renumbered so that they start from 0

### ISSUE THREAD

**Issue by FEA-eng** [imirzov/ccx2paraview#28]
Hi,

I've noticed that when I use this converter and open the vtk file in ParaView, node and element numbers start from 0 instead of 1 like in the input file. I thought that it was a fault of ParaView but its dev told me that the converter itself does it. It can be a problem when exporting results of ParaView operations at nodes and cells (e.g. to map them to a mesh). Would it be possible to change this behavior ?

**Comment by imirzov** [comment]
Hi,

Yes, I renumbered nodes, because in VTK nodes are numbered starting from 0, not from 1. Moreover, VTK support only continuous numbering.

https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf

"Indices are 0-offset. Thus the first point is point id 0."

**Comment by imirzov** [comment]
...and I do not know if this behavior could be changed. And I have no time to test it. Sorry. Try yourself.
