### ISSUE TITLE
Principal stress orientation array in glyph paraview

### ISSUE THREAD

**Issue by iingLK** [imirzov/ccx2paraview#30]
Hi,

I'm using "view vec" in cgx to produce so-alike stress trajectory. How can i simulate it using paraview .vtu using glyph filter? in paraview i cannot see it in orientation array (i can only see displacement). i notice that principal stress are post-produce. ty, sorry for my bad english.

and i think i cannot get ccx "worstPS" in vtu produced file?

**Comment by imirzov** [comment]
Sorry, but Paraview support is not provided here. You'd better ask here:
https://discourse.paraview.org/c/paraview-support/7

**Comment by iingLK** [comment]
I'm sorry for the confusion. I'm using ccx2paraview to produce the vtu file that's why im asking here. i notice that in vtu that produced by ccx2paraview;
1. worstPS (S_Principal title) not convert by ccx2paraview, only Max, Mid, Min (PS1, PS2, PS3). The magnitude not sync with the worstPS.
2. There is no vector information in regard S_principal Max, Mid, Min. I notice it when i make glyph, glyph-orientation array only shown displacement. 

Thank you.

**Comment by xyont** [comment]
hi, you may look into [this ](https://hvlanalysis.blogspot.com/2023/07/principal-stress-plots-with-mecway-and.html)Paraview plugins (state file)

**Comment by iingLK** [comment]
Hi, thank you for the information, i can produce the principal stress now. Using vtu produced by ccx2paraview (input frd file, using ccx prepomax). I just editing some minor change for the stress component. attached screenshot from paraview and cgx. it will be the same if had color to vector implementation.

> hi, you may look into [this ](https://hvlanalysis.blogspot.com/2023/07/principal-stress-plots-with-mecway-and.html)Paraview plugins (state file)

![Screenshot - 2023-08-22 , 10_56_22 - 00011](https://github.com/calculix/ccx2paraview/assets/7983118/f9f7ff3e-7ac4-4a7b-bc1e-6374ed81608d)
![Screenshot - 2023-08-22 , 10_58_30 - 00013](https://github.com/calculix/ccx2paraview/assets/7983118/bbe7d18b-3250-40ed-bdb3-dcada2170188)
