### ISSUE TITLE
input file to paraview

### ISSUE THREAD

**Issue by carlomontec** [imirzov/ccx2paraview#4]
Hi, do you know how can I get a input deck to visualize in Paraview? is it possible with your (awesome) ccx2paraview? I would be interested in observe CLOAD nodal forces as vectors just like the CGX -c mode, I think it could be useful to check correct setup in models.

Thank you for your work!

**Comment by imirzov** [comment]
Hi, sorry, I just don't know how it looks like in CGX - I'm not using it at all.
And I don't know if it's possible to import INP to Paraview. IMHO no.
But you can calculate your INP, convert to VTU with this converter, then open results in Paraview and finally visualize your nodal force.

**Comment by imirzov** [comment]
Yep, you can try FEM module of the FreeCAD - it can visualize boudnary conditions and loads.
Or try Abaqus CAE :)
Also I'm going to develop such features in CalculiX CAE soon:
https://github.com/imirzov/ccx_cae
