### ISSUE TITLE
2D elements QUAD results 

### ISSUE THREAD

**Issue by fasmoe** [imirzov/ccx2paraview#7]
It seems ccx used brick elements instead of direct 2D elements for the analysis. When output the results, is that possible to convert the nodes and elements number back to the original 2D nodes and elments numbers?

**Comment by imirzov** [comment]
Looks like I don't understand the question. Please, have a look at ./examples/elements. After conversion 2D (shell) remain the same including numbering. For example, CPS3.vtu and CPS4.vtu represent shell element after conversion. If you open CPS3.frd or CPS4.frd in the CGX - you'll see shell elements again. So, conversion to brick during calculation doesn't affect the result.

**Comment by fasmoe** [comment]
Sorry, my fault. After double checking the user manual, i figured out how to solve this. Please help to delete this issue to avoid confusion to others. 

Many thanks.
