### ISSUE TITLE
How to open multiple files created for multiple time steps at once in ParaView?

### ISSUE THREAD

**Issue by prasadadhav** [imirzov/ccx2paraview#8]
Hello,

I am really glad I found this because I am new to CCX and CGX, but I have experience with ParaView. Also, I have some issues with visualizing results using `cgx -v file_name.frd`.

I was able to use it on one of my results.
I opened the final time step(500th-time step) and confirm that the results I am seeing in ParaView. 
I read your warning about multiple files being created for each time step.

Is it possible to open all the files at once?

I don't know if I should open a new issue for this or not since I am a new user.
Is it possible to see the deformed shape in ParaView?

In any matter, I am really glad I found this since this can at least work as a temporary fix for my problems until I figure out CGX.

Thank you @imirzov for `ccx2paraview`.

PS: Here are the results
![dispU_flap_500](https://user-images.githubusercontent.com/27627601/79545033-476a0d80-8090-11ea-9843-059e0fd2694c.png)

![displ_plot](https://user-images.githubusercontent.com/27627601/79545063-5bae0a80-8090-11ea-9dbc-e698a40b690a.png)

Here,you can see the space which occupies the flap being deformed, but would be nice to see the first image deformed.
![Flap_FSI 0050](https://user-images.githubusercontent.com/27627601/79545107-73858e80-8090-11ea-8576-ecffdc5b24d1.png)

**Comment by imirzov** [comment]
Dear Alphaoo1,
Thank you for using this converter and for sharing your results!

The command "./ccx2paraview jobname.frd vtu" should produce additional file in XML format - the PVD file. Open it in Paraview to read data from all time steps (all VTU files) at ones.

To see deformed shape in Paraview use filter "Warp by vector".

**Comment by prasadadhav** [comment]
Thank you very much @imirzov.
This will help. me a lot.

I was able to get the results. 

Here are the results for the structure and the corresponding fluid.

![out1](https://user-images.githubusercontent.com/27627601/79616783-2c39e500-8106-11ea-8486-b3903f09d218.gif)

![flap_FSI_Fluid](https://user-images.githubusercontent.com/27627601/79616633-cf3e2f00-8105-11ea-9f08-2de3d5ae4fa3.gif)
