### ISSUE TITLE
Thoughts on creating a pip\conda package of ccx2paraview? 

### ISSUE THREAD

**Issue by Krande** [imirzov/ccx2paraview#9]
Hi,

thank you for sharing the ccx2paraview code! I was just curious about your thoughts on creating a pip (or conda if that is preferable) package of ccx2paraview? 

Having a distributable python package of ccx2paraview seems like something that could make it a bit easier to keep track of package versions when building docker images containing ccx (which is something I am working on)! if you want I can create a pull request with a pypi pipeline setup. Or if you prefer to keep the repo focused on its current tasks, I completely understand and I will instead continue with [my fork of ccx2paraview](https://github.com/Krande/ccx2paraview). 

Let me know what you think,

Kind Regards
Kristoffer

**Comment by imirzov** [comment]
Dear Kristoffer,

Thank you for improving this program! I think GitHub is about cooperation, and despite I have no idea what are conda and docker, please you may send your pull request. But...

I had a look on changes you've made:
https://github.com/calculix/ccx2paraview/compare/master...Krande:master
And I wouldn't like to merge everything. Can't believe that you've improved all 1599 files. If you are ready to search for some kind of compromise, please, first revert back all examples. Your pull request should contain only files you've changed.

Second, please, strictly follow my folder structure - I've updated it. In your repo I don't like "ccx2paraview/src/ccx2paraview/" - it should be just "ccx2paraview/src/".

Please, continue this thread when done.

**Comment by Krande** [comment]
Aha, I did not really intend to do more than just a minor re-structuring of the src folder. The total number of files changed is probably just a side-effect of my IDE adding some newlines (or something like that) during a git refresh. I will fix it so that it does not happen again.

I agree with your comments regarding the folder re-structuring. I will create a pull request with a minimum number of modifications. I would also like to add a azure pipeline file to test a CI pipeline for automatically producing the pypi package from github. Do you guys have a Azure Devops organization or should I just use a temporary one?

**Comment by imirzov** [comment]
Answered in a pull request.

**Comment by imirzov** [comment]
Now there is ccx2paraview package for pip:
https://pypi.org/project/ccx2paraview/
